### ISSUE TITLE
lostphp 发布的 Asar 工具，是开源软件 WinAsar 的早期版本

### ISSUE THREAD

**Issue by aardio** [nwdxlgzs/asar-manager#2]
@nwdxlgzs 
lostphp 发布的 Asar 工具，是从 aardio 范例源码里直接复制粘贴出来的 WinAsar 早期版本，没有做任何改进，他官网上的说明都是一字不漏的复制自我写的帖子：http://bbs.aardio.com/forum.php?mod=viewthread&tid=22100&highlight=asar

lostphp 显然违反了 aardio 开源协议条款：
**2、您可以基于任何目的(包括商用、修改及重分发）免费使用本软件开源代码。您不可以篡改这些开源代码的原始信息，不可以声明您编写最初的版本（包含明示或暗示的导致混淆原始作者的侵权行为）**。

WinAsar 是开源软件，已发布于：
https://github.com/aardio/WinAsar

**Comment by nwdxlgzs** [comment]
> @nwdxlgzs
> lostphp 发布的 Asar 工具，是从 aardio 范例源码里直接复制粘贴出来的 WinAsar 早期版本，没有做任何改进，他官网上的说明都是一字不漏的复制自我写的帖子：http://bbs.aardio.com/forum.php?mod=viewthread&tid=22100&highlight=asar
> 
> lostphp 显然违反了 aardio 开源协议条款：
> **2、您可以基于任何目的(包括商用、修改及重分发）免费使用本软件开源代码。您不可以篡改这些开源代码的原始信息，不可以声明您编写最初的版本（包含明示或暗示的导致混淆原始作者的侵权行为）**。
> 
> WinAsar 是开源软件，已发布于：
> https://github.com/aardio/WinAsar

readme.md已经更正。

**Comment by nwdxlgzs** [comment]
感谢

**Comment by aardio** [comment]
感谢更正
